### ISSUE TITLE
Missing anniversary step

### ISSUE THREAD

**Issue by mblanke** [andrewnordlund/backpayCalc#31] opened 2021-03-10 14:12 UTC
When using the calculator I entered my start date 2018/02/12 and calculate till today. I would have 3 step increases and the calculator only does 3.

**Comment by andrewnordlund** [comment] 2021-03-10 15:07
Really?  I'm getting all 3 when using the same data:
![backpay-2018-02-12-2021-03-10](https://user-images.githubusercontent.com/1805963/110649886-09824600-8188-11eb-9917-d2426b704b9a.png)

I've tried different levels and starting salaries and I always get the same thing.  (Using start date of 2018-02-12, stop calculating on 2021-03-10)

Could you take some screenshots to show what you're entering, and what you're getting?

**Comment by mblanke** [comment] 2021-03-10 15:29
If I started in 2018, I’d have an anniversary in 2019,2020 and 2021 which
puts me at step 7  (I started step 4 CS-03)

**Comment by mblanke** [comment] 2021-03-10 15:29
BTW awesome job for putting this together, I know a lot of people will be
looking for something like this.

**Comment by mblanke** [comment] 2021-03-10 15:34
This might help for a pay grid. I used this based on the CRA CS increase
that had 2 increases within the same year

Step 1 Step 2 Step 3 Step 4 Step 5 Step 6 Step 7 Step 8
2017  $ 83,147.00  $ 86,010.00  $ 88,874.00  $ 91,740.00  $
94,602.00  $           97,462.00  $         100,325.00  $ 103,304.00
2018  $ 83,812.18  $ 86,698.08  $ 89,584.99  $ 92,473.92  $
95,358.82  $           98,241.70  $         101,127.60  $ 104,130.43
2018  $ 85,488.42  $ 88,432.04  $ 91,376.69  $ 94,323.40  $
97,265.99  $         100,206.53  $         103,150.15  $ 106,213.04
2019  $ 85,659.40  $ 88,608.91  $ 91,559.45  $ 94,512.05  $
97,460.52  $         100,406.94  $         103,356.45  $ 106,425.47
2019  $ 87,372.58  $ 90,381.08  $ 93,390.63  $ 96,402.29  $
99,409.73  $         102,415.08  $         105,423.58  $ 108,553.98
2020  $ 88,683.17  $ 91,736.80  $ 94,791.49  $ 97,848.32  $
100,900.88  $         103,951.31  $         107,004.94  $ 110,182.29
1.008 .8%
1.02  Dec 2018 2%
1.002 .2%
1.02  Dec 2019 2%
1.015  Dec 2020 1.5%


https://pipsc.ca/groups/cs/cs-last-offer-information-package-november-2020

**Comment by andrewnordlund** [comment] 2021-03-10 15:46
Oh crud!  I see it now!  I'll look into that.

Dang it.  I'm at _two_ conferences this week!  I'm not sure when I can get to this.  But you won't be the only one with this issue, so I should fix it asap.

**Comment by mblanke** [comment] 2021-03-10 16:05
There is seriously no rush. If I was a coder at all I'd offer to help

**Comment by andrewnordlund** [comment] 2021-03-10 17:56
Could you go ahead and check on the other server if it works?  It seems to with me:

https://www.nordburg.ca/calculators/backpayCalc/2018/backpayCalc.html

**Comment by mblanke** [comment] 2021-03-10 18:05
Looks good to me, I'm just wondering how you calculate the increase.

**Comment by andrewnordlund** [comment] 2021-03-10 18:17
Basically, each period of time with a different rate of pay is treated as a period.  I have an array of periods.  I start with the three pay period in the CA (Dec 22, 2018 to Dec 21, 2019 for example).  Each period is associated with a rank and step. Each rank and step have a daily rate of pay from the old collective agreement.

Each period is also associated with a percentage of pay increase in the new CA vs the old CA.  I hard-code the percentage increases in when we get a new CA.

Then I add anniversary dates, acting periods, promotions, and leave-without-pay periods.  Then I add overtimes and lump sum payments.  (Promotions clear out all old anniversary dates starting from the promotion date going forward, and add new anniversary dates.  Acting periods keep track of anniversary dates at the substantive position so when the acting period is over, it goes down to the right step.)

Then it goes through each period, and for each period it goes day by day checking if it's a weekday.  If so, add another's day pay at the rate determined by the current period in the old CA, and the new CA.  Add them all up and the end and display the results in a handy dandy table.

I can also see why Phoenix is so prone to mistakes!  It has to do all this for us, and several other CA's, and all these different scenarios; part time work, different tax rules per province, etc. etc. etc.

**Comment by mblanke** [comment] 2021-03-10 18:41
I'm a little bored at work so I'm taking a look at the increases and I'm
trying to mirror the CRA way they calculated the increase, but it's not
calculating it properly. I'm just playing around by no means change the
script



[image: image.png]

periods = [{startDate : "2018-12-22", "increase":0.80, "reason":
"Wage Adjustment", "multiplier" : 1},
                   {startDate : "2018-12-22", "increase":2.00, "reason":
"Contractual Increase", "multiplier" : 1},
                   {startDate : "2019-12-22", "increase":0.20, "reason":
"Wage Adjustment", "multiplier" : 1},
                   {startDate : "2019-12-22", "increase":2.00, "reason":
"Contractual Increase", "multiplier" : 1},
                   {startDate : "2020-12-22", "increase":1.50, "reason":
"Contractual Increase", "multiplier" : 1}];
        level -= 1;

**Comment by andrewnordlund** [comment] 2021-03-10 18:50
Keep in mind that CRA has a different bargaining agent than non-CRA CS's.  CRA CS's have different pay rates.  So, our numbers will be different.

**Comment by andrewnordlund** [comment] 2021-03-10 18:50
Where are you getting this?
periods = [{startDate : "2018-12-22", "increase":0.80, "reason":
"Wage Adjustment", "multiplier" : 1},
                   {startDate : "2018-12-22", "increase":2.00, "reason":
"Contractual Increase", "multiplier" : 1},
                   {startDate : "2019-12-22", "increase":0.20, "reason":
"Wage Adjustment", "multiplier" : 1},
                   {startDate : "2019-12-22", "increase":2.00, "reason":
"Contractual Increase", "multiplier" : 1},
                   {startDate : "2020-12-22", "increase":1.50, "reason":
"Contractual Increase", "multiplier" : 1}];
        level -= 1;

**Comment by mblanke** [comment] 2021-03-10 19:03
I know the rates are different but they applied the percentages in a manner
how the PIPSC one might be. yearly increase and wage adjustment..

**Comment by mblanke** [comment] 2021-03-10 19:04
i downloaded your git and edited it to see if I could play with the
calculations..

**Comment by andrewnordlund** [comment] 2021-03-10 19:09
From what I can tell from what you have above, for the first two increases, first they increase by .8% and then 2% on that?  Then next year .2% then 2% on that?
It seems like that would add compounding.  Not that I would object....more moola in our pockets.  :)

I guess we'll have to wait for the new pay rates to be published to find out how it's done.

**Comment by mblanke** [comment] 2021-03-10 19:12
That’s how the cra website describes how they did the increases.
Sounds good   Just shitty that I’d see maybe 45% of that after tax

**Comment by andrewnordlund** [comment] 2021-03-10 19:31
Tell me about it.  Last year I acted for a year, and did a ton of OT in April.  My gross income went up a lot, but my net income only went up a little.

Since the issue is fixed, I'll close this issue now.

**Closed as completed by andrewnordlund** 2021-03-10 19:31 UTC

**Comment by mblanke** [comment] 2021-03-10 19:35
Sounds good.

**Comment by andrewnordlund** [comment] 2021-03-10 19:39
Say....out of curiosity, where did you hear about this calculator?  the PIPSC CS Facebook group?

**Comment by mblanke** [comment] 2021-03-10 20:14
It’s on a Reddit thread

**Comment by andrewnordlund** [comment] 2021-03-10 20:17
What?!  Seriously?   Can you put the URL here?  I wanna see this.

**Comment by mblanke** [comment] 2021-03-10 20:19
Sure, here it is.

https://www.reddit.com/r/CanadaPublicServants/comments/lxp1qe/cs_retro_pay_calculations_for_new_collective/

**Comment by mblanke** [comment] 2021-03-22 14:28
Just came across this calculation of the CS increases.

https://inspection.canada.ca/about-cfia/job-opportunities/hr-information/rates-of-pay/excluded-employees/eng/1341175551516/1341175753462#cs

**Comment by andrewnordlund** [comment] 2021-03-22 16:01
Oh yeah, I saw that last night and made the fix.  Looks like I didn't bother creating an issue for it.

But there's still a major bug if you were acting on the first day of the new CA, it ignores that acting period.  The short term fix is to start the acting period on the first day of the new CA.

**Comment by mblanke** [comment] 2021-03-22 16:32
It’s quite the elaborate calculator you made. Good on you.  Glad I wasn’t
acting

**Comment by mblanke** [comment] 2021-03-25 11:47
Here is the new CA
