### ISSUE TITLE
Missing i18n entry if choose start date on a December 22

### ISSUE THREAD

**Issue by Coollick** [andrewnordlund/backpayCalc#98] opened 2024-01-03 14:01 UTC
Hello,

Tiny bug or omission.

Ex: If you choose a start date that falls on a December 22, you end up with an empty result table.
[https://andrewnordlund.github.io/backpayCalc/2021/backpayCalc.html?lvl=2&stp=7&strtdt=2014-12-22&enddt=2024-03-17](https://andrewnordlund.github.io/backpayCalc/2021/backpayCalc.html?lvl=2&stp=7&strtdt=2014-12-22&enddt=2024-03-17)

Uncaught TypeError: Cannot read properties of undefined (reading 'en')
    at calculate (backpayCalc.js:1691:113)
    at HTMLInputElement.startProcess (backpayCalc.js:512:2)
    at handleHash (backpayCalc.js:316:11)
    at init (backpayCalc.js:174:2)
    at HTMLDocument.getDataFile (backpayCalc.js:2142:3)

Looks to me like there is a missing entry in i18n.json for "Contractual Increase & Anniversary Increase".

Cheers,

**Comment by andrewnordlund** [comment] 2024-01-05 14:48
Let me know if it works now.

I think this is a duplicate of #97 

Thanks for the detailed error reporting.  :)

**Comment by Coollick** [comment] 2024-01-05 20:53
It works, thanks

**Closed as completed** 2024-01-07 14:49 UTC
